"""SRLM step format: prompt construction and robust parsing of model steps.

A step generated by the model looks like:

    <|thought|> short reasoning <|program|>
    ```python
    hits = search_context(r"(?i)our services")
    print(hits[:3])
    ```
    ```json
    {"confidence": 82.5}
    ```
    <|end|>

The terminal step calls FINAL(value) inside its program.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field

CONFIDENCE_INSTRUCTION = (
    'IMPORTANT: At the end of your response, you MUST include your confidence in your answer using this exact '
    'JSON format on a new line: ```json {"confidence": <number between 0.000 and 100.000 with up to 3 decimal '
    'points>} ``` Be precise and nuanced in your confidence assessment.'
)

_CODE_RE = re.compile(r"```(?:python|py)?\s*\n(.*?)```", re.S)
_CONF_BLOCK_RE = re.compile(r"```json\s*(\{[^`]*?\})\s*```", re.S | re.I)
_CONF_LOOSE_RE = re.compile(r"[\"']?confidence[\"']?\s*[:=]\s*([0-9]+(?:\.[0-9]+)?)", re.I)


@dataclass
class ParsedStep:
    thought: str = ""
    code: str = ""
    confidence: float | None = None
    raw: str = ""
    format_ok: bool = True
    issues: list[str] = field(default_factory=list)


def parse_confidence(text: str) -> float | None:
    """Parse the fenced JSON confidence block (falls back to a loose pattern). Valid range (0, 100]."""
    val = None
    for m in _CONF_BLOCK_RE.finditer(text):
        try:
            obj = json.loads(m.group(1))
            if isinstance(obj, dict) and "confidence" in obj:
                val = float(obj["confidence"])
        except (ValueError, TypeError):
            continue
    if val is None:
        ms = _CONF_LOOSE_RE.findall(text)
        if ms:
            try:
                val = float(ms[-1])
            except ValueError:
                val = None
    if val is None or not (0.0 < val <= 100.0):
        return None
    return round(val, 3)


def parse_step(raw: str) -> ParsedStep:
    p = ParsedStep(raw=raw)
    text = raw.replace("<|step|>", "").replace("<|end|>", "")
    thought_part, sep, rest = text.partition("<|program|>")
    if not sep:
        p.issues.append("missing <|program|>")
        rest = text
    p.thought = thought_part.replace("<|thought|>", "").strip() if sep else ""
    conf_free = _CONF_BLOCK_RE.sub("", rest)
    codes = _CODE_RE.findall(conf_free)
    if codes:
        p.code = "\n".join(c.strip("\n") for c in codes)
    else:
        p.issues.append("missing ```python block")
        p.code = conf_free.strip()
    p.confidence = parse_confidence(rest if sep else text)
    if p.confidence is None:
        p.issues.append("missing/invalid confidence")
    p.format_ok = not p.issues
    return p


def render_step(thought: str, code: str, confidence: float | None) -> str:
    """Canonical text of a step (used for SFT targets and the template policy)."""
    conf = "" if confidence is None else f'\n```json\n{{"confidence": {confidence:.3f}}}\n```'
    return f"<|thought|> {thought.strip()} <|program|>\n```python\n{code.strip()}\n```{conf}\n<|end|>"


def summarize_vars(variables: dict) -> str:
    parts = []
    for k, v in variables.items():
        if isinstance(v, str):
            parts.append(f"{k}: str ({len(v)} chars)")
        elif isinstance(v, dict):
            parts.append(f"{k}: dict ({len(v)} keys: {', '.join(list(map(str, v))[:5])}{'…' if len(v) > 5 else ''})")
        elif isinstance(v, list):
            parts.append(f"{k}: list ({len(v)} items)")
        else:
            parts.append(f"{k}: {type(v).__name__} = {str(v)[:80]}")
    return "; ".join(parts)


def build_prompt(task_name: str, query: str, variables: dict, history: list[dict], helper_doc: str,
                 max_obs_chars: int = 1200) -> str:
    """Prompt for the next step: query + short state + this program's previous steps and outputs."""
    lines = [f"<|user|> TASK: {task_name}", f"QUERY: {query}", f"STATE: {summarize_vars(variables)}",
             f"HELPERS:\n{helper_doc}"]
    for h in history:
        obs = h["observation"]
        if len(obs) > max_obs_chars:
            obs = obs[:max_obs_chars] + "…[truncated]"
        lines.append(f"<|step|>{h['text']}\n<|output|> {obs}")
    lines.append(CONFIDENCE_INSTRUCTION)
    lines.append("<|step|>")
    return "\n".join(lines)
